name: "CI (Integração Contínua): primeira-action"

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

# definindo o que será executado
jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a list file
        run: ls -la
